In [2]:
import numpy as np

In [6]:
arr = np.arange(1, 11)
print(arr[arr % 2 == 0])


[ 2  4  6  8 10]


In [7]:
matrix = np.array([[2, 3], [4, 5]])
print(matrix.T)  # Transpose

[[2 4]
 [3 5]]


In [10]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
print(a + b)

[11 22 33 44]


In [11]:
arr = np.array([10, 20, 30, 40])
print(arr[arr > 20])

[30 40]
